### ISSUE TITLE
Datatable Checklist

### ISSUE THREAD

**Issue by davidruvolo51** [davidruvolo51/accessibleshiny#1]
To do list for the datatable function.

- [x] **css**: integrate css from other repository. Maybe sass files would be better?
- [x] **css for cell values**: using the new helper function `cell_attribute`, create corresponding css classes and/or evaluate the naming system for classes. This will need further discussion as to if this is appropriate for the scope of this package as conditional formatting is creates more accessibility concerns.
- [x] **fix logic for helper functions**: There's likely a better way to handle the evaluating the classes and data types of cell values.
- [x] **integrate module testing**: integrate the test script from the other repo
- [x] **Create wiki**: create a new wiki for this package and add documentation for this function

**Comment by davidruvolo51** [comment]
Commit 00d5c71 includes the restructuring of the `css` folder to `assets` to align with the html dependency approach of adding css files to shiny apps. However, the function `render_with_dependencies` does not display parsed styles. More reading on html dependencies is needed.

**Comment by davidruvolo51** [comment]
Commit b2085d6 fixes the first checklist item where html dependencies were not parsed by the DOM. Likely a weird issue when building the package in radian environment. Stick with `R CMD build [packagename]`

**Comment by davidruvolo51** [comment]
Draft of wiki has been created. Documentation is based on `man` files.

**Comment by davidruvolo51** [comment]
I'm ticking the item `css for cell values` option. Commit 8380500 (not pulled to master yet) introduced the `style` argument as well as improved the class names system for table elements and cell values. I think it is better to expose the underlying class names and provide examples for formatting tables rather than providing them in the package itself. It seems to be beyond the scope of this project to provide formatting for cell values as a default. See wiki for more information and to view an example application.

**Comment by davidruvolo51** [comment]
Commit 88cc09f introduces unit testing for the function datatable. See path `tests/` for more information. A number of tests were written with the purpose of evaluating html markup of the table element. See the file `tests-datatable.R` to view the specific tests.

**Comment by davidruvolo51** [comment]
Commit e43921c finishes the task and preps the package for merging with the master branch. The logic for evaluating classes is fine for now. This may want to be revisited in the future once the package continues development.
