### ISSUE TITLE
Performance Concerns & Optimizations

### ISSUE THREAD

**Issue by davidruvolo51** [davidruvolo51/accessibleshiny#6]
Generating the markup does a fairly nice job with smaller datasets. However, there are noticeable performance issues for larger datasets (i.e., > 1000 rows). The ideal use of the `datatable` function is to prevent production-ready, accessible datatables. It isn't really ideal for larger datasets as data tables in production apps should use smaller datasets. Regardless, the evaluation of cells and corresponding markup should be optimized. Since `purrr` is already a package dependency, markup generating functions should incorporate map functions. 

TODO

- [x] Reduce the number of evaluations that are performed
- [x] Integrate better mapping functions for generating cell-level markup

**Comment by davidruvolo51** [comment]
Commit 6dcd32d introduces an early draft of the datatable function rewritten with purrr. This will likely be a better option in the long run. The TODO list in the first post is now complete. New tasks are assigned below.

- [ ] Reduce the number of evaluations that are performed
- [ ] Adjust lower-level functions to process options

**Comment by davidruvolo51** [comment]
Commit decd9b7 adds the rewrite of the datatable function and helpers using purrr. Using base functions is a good approach, but there are some performance issues with larger tables. The number of evaluations were reduced and child functions where split into several lower-level functions.

For now, a custom render and output functions are not needed as this function isn't a wrapper around an existing library. It is recommended to use existing `renderUI` or `insertUI` for rendering tables to the client.

I think some css adjustments are need. When the window size is less than the breakpoint, I would like the inline column names and cell content to be a bit more evenly spaced (50/50). I would like to the text to wrap within their respective space rather than breaking onto a new line and expanding to 100%. I think `display: flex` and `word-break` should do it.

**TODO**

- [ ] Adjust width of inline column name and cell value (ideally `50%` and `50%`)
- [ ] Adjust word break so it stays within `50%`.

**Comment by davidruvolo51** [comment]
Commit 2c399f6 introduces CSS changes to the datatable component. Inline column names are now set to 50% of the width. Table cells are also set to `display: flex` and `word-break: break-word`. Padding was reduced as well.
